### ISSUE TITLE
Allow referencing SCMProvider from another namespace

### ISSUE THREAD

**Issue by alexymantha** [argoproj-labs/gitops-promoter#308]
Currently, all the resources need to be in the same namespace. I would like to be able to configure the SCMProvider and SCM secrets in a different namespace from where the GitRepository and PromotionStrategy are defined. 

What I am trying to do is allow end-users to configure their promotion strategies in their own namespace, but I do not want them to have access to the SCM secrets

```
team-a-namespace                 | promoter-system
- GitRepository: my-team-repo	 | - SCMProvider
- PromotionStrategy              | - Secret: credentials for the SCM
```

As far as I can tell, we should be able to just add a `namespace` field to the ref:

```yaml
apiVersion: promoter.argoproj.io/v1alpha1
kind: GitRepository
metadata:
  name: gitops-pdx-canada
  namespace: team-a-namespace
spec:
  gitlab:
    owner: my-org
    name: gitops
  scmProviderRef:
    name: github
    namespace: promoter-system
```
and then use it to fetch the SCMProvider
