### ISSUE TITLE
CTP additional status fiedls

### ISSUE THREAD

**Issue by zachaller** [argoproj-labs/gitops-promoter#333]
We will need some additional status fields on the CTP one such field I can think of today to help drive some UI this issue will collect some thoughts on that.

* Top level History Object - Stores things like when we have merged PRs we might also want this to reconcile when PR's merge to capture states of checks when forced merged via SCM
* PullRequest ID - we might want to store the pull requests id's possibly under some top parent history type object to see timestamps and possibly some statuses of proposedChecks at time of merge.
*  CommitStatus and Author Messages of both Code Repo and optional additional repos

**Comment by zachaller** [comment]
Pre-req: https://github.com/argoproj-labs/gitops-promoter/issues/328

**Comment by crenshaw-dev** [comment]
Done 

```yaml
status:
  pullRequest:
    id: "848"
    state: open # open, closed, or merged
    url: https://github.com/org/repo/pull/848
    prCreationTime: 2023-10-01T00:00:00Z
  history:
    # Recent promotions merged by the controller (newest first, at most 5 entries).
    - active:
        # same as top-level active
      proposed:
        # same as top-level proposed, without dry
      pullRequest:
        id: "847"
        prMergeTime: 2023-09-01T00:00:00Z
        url: https://github.com/org/repo/pull/847
```
