### ISSUE TITLE
Add conditions tooling and conditions to current controllers.

### ISSUE THREAD

**Issue by zachaller** [argoproj-labs/gitops-promoter#345]
We should look into some common open source tooling within k8s ecosystem to help manage conditions before writing our own.

https://pkg.go.dev/sigs.k8s.io/cluster-api/util/conditions
https://pkg.go.dev/k8s.io/apimachinery/pkg/api/meta#FindStatusCondition

```
 conditions:
    # for PromotionStrategy
    - type: Ready
      # probably just a dumping ground for errors
    - type: PromotionsCompleted
      status: "True"
      reason: PromotionsCompleted
      message: All environments running latest commit, no new commits detected
    - type: PromotionsCompleted
      status: "False"
      reason: PromotionsPending # Error, RateLimited, CTPMissing?
      message: Not all environments running latest commit, currently promoting <env>

    # for CTP
    - type: ProposedCommitStatusesSucceeded
      status: "True"
      reason: ProposedCommitStatusesSucceeded
      message: All proposed commit statuses succeeded
    - type: ProposedCommitStatusesSucceeded
      status: "False"
      reason: SomeCommitStatusesMissing # SomeCommitStatusesNotSucceeded (message specifies error, failure, pending, etc.)
      message:
    - type: ActiveCommitStatusesSucceeded
 ```
